# Generated by Django 4.1.3 on 2022-11-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_rename_data_added_entry_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_added',
            new_name='data_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date_added',
            new_name='data_added',
        ),
    ]
